[package]
name = "ayed-tui"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ayed-core = { path = "../ayed-core/" }

crossterm = "0.28"
